### ISSUE TITLE
Missing dependencies for keras preprocessing

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/mit-d3m#20]
* mit-d3m version: 0.2.1
* Python version: 3.7.7
* Operating System: 10.15.7

### Description

Trying to load an image dataset results in an error. Keras dependency as specified results in missing tensorflow dependency. Adding a tensorflow dependency would be really unsatisfying because this should be a lightweight library and keras is only used for `keras.preprocessing.image.{load_img,img_to_array}`

### What I Did

```

from mit_d3m import load_dataset
dataset = load_dataset('124_188_usps')
$ python
Python 3.7.7 (default, Jul 20 2020, 16:35:32) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mit_d3m import load_dataset
>>> dataset = load_dataset('124_188_usps')
Traceback (most recent call last):
  File "/Users/micahsmith/workspace/sandbox/.venv/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/micahsmith/workspace/sandbox/.venv/lib/python3.7/site-packages/mit_d3m/__init__.py", line 151, in load_dataset
    dataset = loader.load(d3mds)
  File "/Users/micahsmith/workspace/sandbox/.venv/lib/python3.7/site-packages/mit_d3m/loaders.py", line 428, in load
    X = self.load_resources(X, resource_column, d3mds)
  File "/Users/micahsmith/workspace/sandbox/.venv/lib/python3.7/site-packages/mit_d3m/loaders.py", line 441, in load_resources
    from keras.preprocessing.image import img_to_array, load_img  # noqa
  File "/Users/micahsmith/workspace/sandbox/.venv/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```

Pip freeze output:
<details>
$ pip freeze
boto3==1.16.41
botocore==1.19.41
cached-property==1.5.2
decorator==4.4.2
funcy==1.15
h5py==3.1.0
jmespath==0.10.0
joblib==1.0.0
Keras==2.4.3
mit-d3m==0.2.1
networkx==2.5
numpy==1.19.4
pandas==1.1.5
psutil==5.8.0
pymongo==3.11.2
python-dateutil==2.8.0
pytz==2020.4
PyYAML==5.3.1
s3transfer==0.3.3
scikit-learn==0.24.0
scipy==1.5.4
six==1.15.0
threadpoolctl==2.1.0
urllib3==1.26.2
</details>

### Discussion

possible resolutions:
- install tensorflow also (this has so many problems with it...)
- pin keras to earlier version
- use keras_preprocessing which is distributed separately
- find alternative implementations of load_img and img_to_array functions

**Comment by csala** [comment]
Interesting.

I would not go for (1) because of what you exposed, and I would not go for (2) either because that may provoke issues in the libraries that use `mit-d3m`.

If works, I vote for (3), since this seems to be the simplest option.

**Comment by micahjsmith** [comment]
I have a patch that installs `keras_preprocessing[image]` and this appears to resolve things
